baseURL = "https://lan.techlancaster.com"
languageCode = "en-us"
title = "TechLancaster"
theme = "ananke"
publishDir = "docs"

[params]
  favicon = ""
  description = "DESCRIPTION"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-orange"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  body_classes = "avenir bg-near-black"
